### ISSUE TITLE
Implement basic Class Diagram

### ISSUE THREAD

**Issue by stephane-segning** [ADORSYS-GIS/e2e-banking-app#3]
- User Story: #1 
- Description: Refer to U.S. for describing and implementing the Class Diagram using the MVC pattern in the Spring Boot Backend.
  - Write only models classes
  - To do that, you should create a new package next to the main class folder and place the content inside of it

**Comment by NkwaTambe** [comment]
Hello sir @stephane-segning  please can you enlighten me more on these ticket..

**Comment by NkwaTambe** [comment]
Hello sir @stephane-segning  should i add annotations to innitialize a DB since we are focusing on the model classes??

**Comment by NkwaTambe** [comment]
Because i was thinking , following the mvc pattern, the model functions in updating and manipulating data hence works with the Database to do that..

i will need you idea on these sir if you don't mine...
