### ISSUE TITLE
Create a high level description of the Power Payment Backend

### ISSUE THREAD

**Issue by stephane-segning** [ADORSYS-GIS/e2e-banking-app#33]
- Write a document which contains how the PP Backend works, how it's interacting with other components
- Include everything we'll need as technology for the PP backend
- Write it all in a `.md` file, in the `docs` folder

**Comment by Awambeng** [comment]
Good morning prof please i am unable to push my work can you please check the rights.

**Comment by stephane-segning** [comment]
Please fork & create a PR

**Comment by Awambeng** [comment]
Done you can check it at: https://github.com/ADORSYS-GIS/e2e-banking-app/pull/44
